apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: app-namespace
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "DefaultConnection": "Server=mssql-service;Database=S1_Auth;User Id=sa;Password=p4ssw0rD;Encrypt=False"
      },
      "JWT": {
        "SecretKey": "!3h1|pWfVVrXnNJ^0bQ6jDI&%<K\\JpAY",
        "SigningKey": "gRqCoSi0dRinMs9IfIotKt7N0FLZIiN1N64yrLDHvotSD8EDGVeZhPhoPbEXdtX8AJYVrSjzswtKGVWx9ijz9QRWVWIVdpXIEqGoW03HZBxN4VoUBk8Zlxs0Heki7oNZOAmgpvIFbEKKgmBTI7EWJSJw6PtKKW52GR+ZNdHV/C4=",
        "Issuer": "http://localhost",
        "Audience": "http://localhost"
      },
      "Kafka": {
        "BootstrapServers": "kafka-cluster:9092",
        "SendAvatar": {
          "GroupId": "send-avatar-group",
          "Topic": "send-avatar-topic"
        },
        "SendNotification": {
          "GroupId": "send-notification-group",
          "Topic": "send-notification-topic"
        }
      }
    }

