apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  namespace: app-namespace
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "DefaultConnection": "Server=mssql-service;Database=S3_Notification;User Id=sa;Password=p4ssw0rD;Encrypt=False"
      },
      "AuthApiClient": {
        "BaseAddress": "http://auth-service",
        "ValidateToken": "/auth/validate-token"
      },
      "Kafka": {
        "BootstrapServers": "kafka-cluster:9092",
        "SendNotification": {
          "GroupId": "send-notification-group",
          "Topic": "send-notification-topic"
        }
      }
    }